### PR TITLE
Added favorite place (question #5)

### LINKED ISSUE #5: Add example favorite place

### PR DESCRIPTION
**Pull request by sndmnska**
Added my favorite place

### CODE REVIEW

**Comment by Spillahm** [comment]
fixes issue #4

**Comment by Spillahm** [comment]
Everything looks great

**Review by Spillahm — COMMENTED** [review]
looks great

**Review by Spillahm — COMMENTED** [review]
looks great

**Review by alexandreaparks — APPROVED** [review]
All looks great!

**Pull request merged**
